import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {demoAddons} from '../src/addons-catalog.js';
import {primaryProducts,addonRecommendations,addonQuantity,configurationOrderable,changeAddonQuantity} from '../src/addon-model.js';
import {withAddonsApp,withAddonsOrder} from '../deploy/addons.mjs';
import {addonArt} from '../src/addons.js';
const app=readFileSync(new URL('../src/app.js',import.meta.url),'utf8');
const version=app.match(/from ['"]\.\/data\.js([^'"]*)['"]/)[1];
const runtime=file=>import(new URL(`../src/${file}${version}`,import.meta.url));
const {products,findProduct}=await runtime('data.js');
const {defaultConfig,normalizeConfig}=await runtime('order.js');
const store=await runtime('store.js');
const pizza=findProduct('house-pizza'),drink=findProduct('demo-drink-cola'),sauce=findProduct('demo-sauce-garlic');
const line=(product,variantId,qty=1)=>({config:{...defaultConfig(product),variantId},qty});
const small=line(pizza,'small'),large=line(pizza,'large');
assert.equal(demoAddons.length,9);
assert.match(addonArt(drink,drink.variants[0]),/cola-can-330-v1.webp/);
assert.match(addonArt(drink,drink.variants[1]),/cola-bottle-1500-v1.webp/);
assert.match(addonArt({...sauce,image:null}),/addon-art/);
for(const product of demoAddons){for(const variant of product.variants){const photo=variant.image||product.image;assert.ok(photo,'each illustrative SKU has a photo');assert.ok(readFileSync(new URL('../'+photo.replace(/^\.\//,''),import.meta.url)).length>1000);}}
assert.equal(primaryProducts(products).some(product=>product.menuCategory==='drinks'),false);
assert.equal(addonRecommendations([small],products).find(item=>item.productId===drink.id).variantId,'can-330');
assert.equal(addonRecommendations([large],products).find(item=>item.productId===drink.id).variantId,'bottle-1500');
assert.equal(addonRecommendations([{...small,qty:2}],products).find(item=>item.productId===drink.id).variantId,'bottle-1500');
assert.equal(addonRecommendations([small,line(drink,'can-330')],products).length,1);
assert.equal(addonRecommendations([small,line(drink,'can-330'),line(sauce,'cup-50')],products).length,0);
const unavailable=structuredClone(products),cola=unavailable.find(product=>product.id===drink.id);
cola.variants.find(variant=>variant.id==='bottle-1500').available=false;
assert.equal(addonRecommendations([large],unavailable).find(item=>item.productId.startsWith('demo-drink')).variantId,'bottle-1500');
cola.available=false;
assert.ok(!addonRecommendations([small],unavailable).some(item=>item.productId===cola.id));
assert.equal(configurationOrderable(cola,{variantId:'can-330'}),false);
assert.equal(normalizeConfig(drink,{...defaultConfig(drink),variantId:'removed-size'}).variantId,'removed-size');
assert.equal(configurationOrderable(drink,{variantId:'removed-size'}),false);
assert.equal(withAddonsApp(app),app);
const order=readFileSync(new URL('../src/order.js',import.meta.url),'utf8');assert.equal(withAddonsOrder(order),order);
store.clearCart();
const api={...store,findProduct,defaultConfig};
changeAddonQuantity(api,drink.id,'can-330',1);changeAddonQuantity(api,drink.id,'can-330',1);
assert.equal(store.getCart().length,1);assert.equal(addonQuantity(store.getCart(),drink.id,'can-330'),2);
changeAddonQuantity(api,drink.id,'bottle-1500',1);assert.equal(store.getCart().length,2);
store.addLine({...defaultConfig(drink),variantId:'can-330',label:'לאורח'},1);
changeAddonQuantity(api,drink.id,'can-330',1);assert.equal(store.getCart().length,3);assert.equal(store.getCart().find(item=>item.config.label==='לאורח').qty,1);
changeAddonQuantity(api,drink.id,'bottle-1500',-1);assert.equal(store.getCart().length,2);
assert.equal(store.undoRemoveLine().config.variantId,'bottle-1500');
const plain=store.getCart().find(item=>!item.config.label&&item.config.variantId==='can-330');store.updateLine(plain.id,{qty:99});
assert.throws(()=>changeAddonQuantity(api,drink.id,'can-330',1),/99/);
store.clearCart();
for(let i=0;i<40;i++)store.addLine({...defaultConfig(pizza),label:`בדיקה ${i}`},1);
assert.throws(()=>changeAddonQuantity(api,sauce.id,'cup-50',1),/40/);
store.clearCart();
console.log('Add-on checks passed: contextual sizes, availability, explicit replacement, merging, undo and cart limits.');
